[project]
name = "mlbcountswebapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "gspread>=6.1.4",
    "gunicorn>=23.0.0",
    "pandas>=2.2.3",
    "pymongo>=4.10.1",
    "requests>=2.32.3",
]

[tool.ruff]
# Максимальная длина строки
line-length = 88

# Правила, которые будут применяться:
# E, F, W — стандартные ошибки и предупреждения (flake8)
# I — проверки импорта
# B — расширенные проверки от bugbear
# N — соглашения об именовании
# D — проверки docstrings
select = ["E", "F", "W", "I", "B", "N", "D"]

# Игнорируем правило для длинных строк (E501), чтобы не усложнять чтение кода
ignore = ["E501"]

# Исключаем из анализа виртуальное окружение и другие служебные директории
exclude = [".venv", "venv", "migrations"]

[tool.ruff.format]
# Настройки форматирования: стиль кавычек, отступов и окончания строк
quote-style = "double"
indent-style = "space"
line-ending = "auto"
